import type { ProductType, StatCard } from "./types"

import product1 from '@/assets/images/products/1.png'
import product10 from '@/assets/images/products/10.png'
import product2 from '@/assets/images/products/2.png'
import product3 from '@/assets/images/products/3.png'
import product4 from '@/assets/images/products/4.png'
import product5 from '@/assets/images/products/5.png'
import product6 from '@/assets/images/products/6.png'
import product7 from '@/assets/images/products/7.png'
import product8 from '@/assets/images/products/8.png'
import product9 from '@/assets/images/products/9.png'


export const statsData: StatCard[] = [
  {
    id: 'products',
    title: 'Products',
    value: '1,842',
    newCount: '12',
    icon: 'tabler:package',
    iconBg: 'primary',
    iconColor: 'text-primary',
    metric: 'Active Listings',
    metricValue: '12,845',
    metricColor: 'text-primary',
  },
  {
    id: 'orders',
    title: 'Orders',
    value: '1,842',
    newCount: '12',
    icon: 'tabler:shopping-cart',
    iconBg: 'secondary',
    iconColor: 'text-success',
    metric: 'Total Orders',
    metricValue: '45,845',
    metricColor: 'text-success',
  },
  {
    id: 'sales',
    title: 'Sales',
    value: '$9,860',
    newCount: '8.2',
    icon: 'tabler:currency-dollar',
    iconBg: 'success',
    iconColor: 'text-success',
    metric: "Today's Sales",
    metricValue: '$156K',
    metricColor: 'text-success',
  },
  {
    id: 'customers',
    title: 'Customers',
    value: '2,945',
    newCount: '36',
    icon: 'tabler:users',
    iconBg: 'info',
    iconColor: 'text-info',
    metric: 'Total Customers',
    metricValue: '58,320',
    metricColor: 'text-info',
  },
  {
    id: 'revenue',
    title: 'Revenue',
    value: '$12.8M',
    newCount: '12',
    icon: 'tabler:chart-bar',
    iconBg: 'warning',
    iconColor: 'text-warning',
    metric: 'Total Revenue',
    metricValue: '$128.5M',
    metricColor: 'text-warning',
  },
]

export const productData: ProductType[] = [
  {
    id: 'WB-10245',
    image: product1,
    name: 'Wireless Earbuds',
    brand: 'My Furniture',
    sku: 'WB-10245',
    category: 'Electronics',
    stock: 56,
    price: 59.99,
    orders: 124,
    rating: 5,
    reviews: 87,
    status: 'Published',
    lastModified: '18 Apr, 2025 12:24 PM',
    publishedDate: '18 Apr, 2025',
    publishedTime: '12:24 PM',
  },
  {
    id: 'SL-89012',
    image: product2,
    name: 'Smart LED Desk Lamp',
    brand: 'BrightLite',
    sku: 'SL-89012',
    category: 'Home & Office',
    stock: 32,
    price: 39.49,
    orders: 78,
    rating: 4,
    reviews: 54,
    status: 'Pending',
    lastModified: '22 Apr, 2025 09:45 AM',
    publishedDate: '22 Apr, 2025',
    publishedTime: '09:45 AM',
  },
  {
    id: 'RS-20450',
    image: product3,
    name: "Men's Running Shoes",
    brand: 'ActiveWear Co.',
    sku: 'RS-20450',
    category: 'Fashion',
    stock: 120,
    price: 89.0,
    orders: 231,
    rating: 5,
    reviews: 142,
    status: 'Published',
    lastModified: '24 Apr, 2025 03:10 PM',
    publishedDate: '24 Apr, 2025',
    publishedTime: '03:10 PM',
  },
  {
    id: 'FT-67123',
    image: product4,
    name: 'Fitness Tracker Watch',
    brand: 'FitPulse',
    sku: 'FT-67123',
    category: 'Fitness',
    stock: 78,
    price: 49.95,
    orders: 198,
    rating: 4,
    reviews: 89,
    status: 'Published',
    lastModified: '23 Apr, 2025 10:12 AM',
    publishedDate: '23 Apr, 2025',
    publishedTime: '10:12 AM',
  },
  {
    id: 'GM-72109',
    image: product5,
    name: 'Gaming Mouse RGB',
    brand: 'HyperClick',
    sku: 'GM-72109',
    category: 'Gaming',
    stock: 120,
    price: 29.99,
    orders: 243,
    rating: 3,
    reviews: 102,
    status: 'Published',
    lastModified: '19 Apr, 2025 05:56 PM',
    publishedDate: '19 Apr, 2025',
    publishedTime: '05:56 PM',
  },
  {
    id: 'FC-31220',
    image: product6,
    name: 'Modern Lounge Chair',
    brand: 'UrbanLiving',
    sku: 'FC-31220',
    category: 'Furniture',
    stock: 24,
    price: 199.0,
    orders: 38,
    rating: 5,
    reviews: 27,
    status: 'Out of Stock',
    lastModified: '18 Apr, 2025 11:30 AM',
    publishedDate: '18 Apr, 2025',
    publishedTime: '11:30 AM',
  },
  {
    id: 'TY-00788',
    image: product7,
    name: 'Plush Toy Bear',
    brand: 'Softies',
    sku: 'TY-00788',
    category: 'Toys',
    stock: 150,
    price: 15.99,
    orders: 305,
    rating: 4,
    reviews: 120,
    status: 'Published',
    lastModified: '17 Apr, 2025 04:21 PM',
    publishedDate: '17 Apr, 2025',
    publishedTime: '04:21 PM',
  },
  {
    id: 'TV-5588',
    image: product8,
    name: '55" Ultra HD Smart TV',
    brand: 'ViewMaster',
    sku: 'TV-5588',
    category: 'Electronics',
    stock: 64,
    price: 499.0,
    orders: 142,
    rating: 4,
    reviews: 88,
    status: 'Published',
    lastModified: '25 Apr, 2025 10:10 AM',
    publishedDate: '25 Apr, 2025',
    publishedTime: '10:10 AM',
  },
  {
    id: 'IMAC-M3-24',
    image: product9,
    name: 'Apple iMac 24" M3',
    brand: 'Apple',
    sku: 'IMAC-M3-24',
    category: 'Computers',
    stock: 18,
    price: 1399.0,
    orders: 29,
    rating: 5,
    reviews: 16,
    status: 'Pending',
    lastModified: '24 Apr, 2025 02:14 PM',
    publishedDate: '24 Apr, 2025',
    publishedTime: '02:14 PM',
  },
  {
    id: 'SWPX2-GL',
    image: product10,
    name: 'Smart Watch Pro X2',
    brand: 'FitTech',
    sku: 'SWPX2-GL',
    category: 'Wearables',
    stock: 85,
    price: 149.5,
    orders: 197,
    rating: 4,
    reviews: 65,
    status: 'Published',
    lastModified: '23 Apr, 2025 08:00 AM',
    publishedDate: '23 Apr, 2025',
    publishedTime: '08:00 AM',
  },

]