
import type { BasicActivityType, ExpandedActivityType } from './types'
import user1 from '@/assets/images/users/user-1.jpg'
import user10 from '@/assets/images/users/user-10.jpg'
import user2 from '@/assets/images/users/user-2.jpg'
import user3 from '@/assets/images/users/user-3.jpg'
import user4 from '@/assets/images/users/user-4.jpg'
import user5 from '@/assets/images/users/user-5.jpg'
import user6 from '@/assets/images/users/user-6.jpg'
import user7 from '@/assets/images/users/user-7.jpg'
import user8 from '@/assets/images/users/user-8.jpg'
import user9 from '@/assets/images/users/user-9.jpg'


export const basicActivities: BasicActivityType[] = [
  {
    status: 'Add',
    variant: 'info',
    time: 'Today at 08:05:33 am',
    name: 'Olivia Lee',
    avatar: user1,
    action: 'Added a new design asset',
  },
  {
    status: 'Update',
    variant: 'success',
    time: 'Today at 08:48:20 am',
    name: 'Ethan Wong',
    avatar: user2,
    action: 'Updated project timeline',
  },
  {
    status: 'Upload',
    variant: 'primary',
    time: 'Today at 09:12:45 am',
    name: 'Grace Kim',
    avatar: user3,
    action: 'Uploaded design guidelines PDF',
  },
  {
    status: 'Remove',
    variant: 'danger',
    time: 'Today at 09:55:02 am',
    name: 'Noah Smith',
    avatar: user4,
    action: 'Removed outdated document',
  },
  {
    status: 'Comment',
    variant: 'warning',
    time: 'Today at 10:34:10 am',
    name: 'Mia Johnson',
    avatar: user5,
    action: 'Commented on new task board',
  },
  {
    status: 'Approve',
    variant: 'success',
    time: 'Today at 11:03:22 am',
    name: 'Liam Davis',
    avatar: user6,
    action: 'Approved budget request',
  },
  {
    status: 'Add',
    variant: 'primary',
    time: 'Today at 11:40:07 am',
    name: 'Sophia Martinez',
    avatar: user7,
    action: 'Added new member to team',
  },
  {
    status: 'Edit',
    variant: 'warning',
    time: 'Today at 12:18:33 pm',
    name: 'Jack Wilson',
    avatar: user8,
    action: 'Edited task deadline',
  },
  {
    status: 'Reject',
    variant: 'danger',
    time: 'Today at 01:05:11 pm',
    name: 'Ella Moore',
    avatar: user9,
    action: 'Rejected draft submission',
  },
  {
    status: 'Share',
    variant: 'info',
    time: 'Today at 01:43:29 pm',
    name: 'Benjamin Taylor',
    avatar: user10,
    action: 'Shared roadmap document',
  },
  {
    status: 'Upload',
    variant: 'success',
    time: 'Today at 02:15:50 pm',
    name: 'Olivia Lee',
    avatar: user1,
    action: 'Uploaded Q2 reports',
  },
  {
    status: 'Edit',
    variant: 'warning',
    time: 'Today at 02:52:06 pm',
    name: 'Ethan Wong',
    avatar: user2,
    action: 'Edited team description',
  },
  {
    status: 'Delete',
    variant: 'danger',
    time: 'Today at 03:20:44 pm',
    name: 'Grace Kim',
    avatar: user3,
    action: 'Deleted obsolete files',
  },
  {
    status: 'Approve',
    variant: 'success',
    time: 'Today at 03:58:00 pm',
    name: 'Noah Smith',
    avatar: user4,
    action: 'Approved new sprint plan',
  },
  {
    status: 'Add',
    variant: 'primary',
    time: 'Today at 04:36:18 pm',
    name: 'Mia Johnson',
    avatar: user5,
    action: 'Added new project brief',
  },
  {
    status: 'Comment',
    variant: 'warning',
    time: 'Today at 05:14:03 pm',
    name: 'Liam Davis',
    avatar: user6,
    action: 'Left a note on timeline slide',
  },
  {
    status: 'Share',
    variant: 'info',
    time: 'Today at 05:49:57 pm',
    name: 'Sophia Martinez',
    avatar: user7,
    action: 'Shared access to internal repo',
  },
  {
    status: 'Remove',
    variant: 'danger',
    time: 'Today at 06:30:41 pm',
    name: 'Jack Wilson',
    avatar: user8,
    action: 'Removed archived ticket',
  },
  {
    status: 'Upload',
    variant: 'primary',
    time: 'Today at 07:10:59 pm',
    name: 'Ella Moore',
    avatar: user9,
    action: 'Uploaded team performance chart',
  },
  {
    status: 'Create',
    variant: 'success',
    time: 'Today at 07:52:14 pm',
    name: 'Benjamin Taylor',
    avatar: user10,
    action: 'Created a new OKR session',
  },
]

export const expandedActivities: ExpandedActivityType[] = [
  {
    icon: 'tabler:rocket',
    title: 'New Feature Released',
    variant: 'info',
    label: 'Deploy',
    time: 'Today at 3:45 PM',
    description: 'Launched the real-time chat feature across all user accounts.',
    avatar: user6,
    name: 'Natalie Brooks',
    profileUrl: '/pages/profile',
  },
  {
    icon: 'tabler:calendar-event',
    title: 'Team Sync-Up',
    variant: 'secondary',
    label: 'Meeting',
    time: 'Today at 2:00 PM',
    description: 'Reviewed sprint progress and discussed remaining tasks with the dev team.',
    avatar: user4,
    name: 'Oliver Grant',
    profileUrl: '/pages/profile',
  },
  {
    icon: 'tabler:palette',
    title: 'UI Design Review',
    label: 'Design',
    variant: 'success',
    time: 'Today at 1:15 PM',
    description: 'Updated component spacing and colors for improved accessibility.',
    avatar: user9,
    name: 'Clara Jensen',
    profileUrl: '/pages/profile',
  },
  {
    icon: 'tabler:database',
    title: 'Database Optimization',
    variant: 'danger',
    label: 'Backend',
    time: 'Today at 12:30 PM',
    description: 'Improved DB query performance, reducing load time by 35%.',
    avatar: user10,
    name: 'Leo Armstrong',
    profileUrl: '/pages/profile',
  },
  {
    icon: 'tabler:shield-check',
    title: 'Security Audit Completed',
    variant: 'warning',
    label: 'Audit',
    time: 'Today at 11:00 AM',
    description: 'Completed internal security audit with no critical issues found.',
    avatar: user8,
    name: 'Liam Carter',
    profileUrl: '/pages/profile',
  },
  {
    icon: 'tabler:user-plus',
    title: 'New Team Member Joined',
    variant: 'primary',
    label: 'Onboarding',
    time: 'Today at 10:15 AM',
    description: 'Michael Lee has joined the development team as a Frontend Engineer.',
    avatar: user7,
    name: 'Emma Davis',
    profileUrl: '/pages/profile',
  },
  {
    icon: 'tabler:pencil',
    title: 'Documentation Updated',
    variant: 'secondary',
    label: 'Docs',
    time: 'Yesterday at 5:20 PM',
    description: 'Refreshed developer documentation with updated APIs and workflows.',
    avatar: user7,
    name: 'Sophia Reed',
    profileUrl: '/pages/profile',
  },
  {
    icon: 'tabler:check',
    title: 'Task Completed',
    variant: 'success',
    label: 'Done',
    time: 'Yesterday at 3:10 PM',
    description: 'Finished implementation of the email notification system.',
    avatar: user5,
    name: 'Daniel Chen',
    profileUrl: '/pages/profile',
  },
]
